#! /usr/local/bin/perl
use warnings;
use strict;

use DBI;
use DBD::mysql;

my $database = "test";
my $my_cnf = "$ENV{HOME}/.my.cnf";
my $dsn = "DBI:mysql:$database;mysql_read_default_file=$my_cnf";

my $dbh = DBI->connect($dsn);
