#! /usr/local/bin/perl
use warnings;
use strict;

use DBI;
use DBD::mysql;

my $database = "test";
my $my_cnf = "$ENV{HOME}/.my.cnf";
my $dsn = "DBI:mysql:$database;mysql_read_default_file=$my_cnf";

my $dbh = DBI->connect($dsn);

my $table = "foo";
my $column = "monkey";

print "good\n" if $dbh->selectrow_arrayref(qq|SHOW COLUMNS FROM $table LIKE "$column"|);
print "bad\n" if $dbh->selectrow_arrayref(qq|SHOW COLUMNS FROM $table LIKE "notlikely"|);

$dbh->disconnect();
