#! /usr/bin/perl
use warnings;
use strict;

my @animals = qw/
	monkey
	walrus
	gerbil
	giraffe
	aardvark
/;

my @stuff = qw/
	chair
	bathtub
	desk
	rug
/;

for (@animals, @stuff) {
	s/^/david's /;
}

for (@animals) {
	print;
	print "\n";
}
for (@stuff) {
	print;
	print "\n";
}
