#! /usr/local/bin/perl
use warnings;
use strict;

my @words = qw| eenie meenie miney moe |;

for my $word (@words) {
        $word = ucfirst $word;
}

print join "\n", @words;
print "\n";

my $ref = \"monkey";

for my $var ($$ref) {
        $var = "aardvark";
}
print $$ref, "\n";

for ($$ref) {
        s/o/0/g;
}
print $$ref, "\n";
