#! /usr/local/bin/perl
use warnings;
use strict;

package Simian;

sub marine
{
        my $class = shift;
        print "a $class can sometimes swim\n";
}

sub talk
{
        my $class = shift;
        print "a $class says stuff\n";
}

package Monkey;
our @ISA = qw| Simian |;

sub talk
{
        my $class = shift;
        print "a $class says 'ook!'\n";
}

package main;

Simian->marine;
Monkey->marine;
Simian->talk;
Monkey->talk;
