#! /usr/local/bin/perl
use warnings;
use strict;

my @onetwothree = (1, 2, 3);

my ($one, $two, $three) = @onetwothree;
print "one: $one, two: $two, three: $three\n";

undef $one; undef $two; undef $three;
(undef,$two,$three) = @onetwothree;
print "one: $one, two: $two, three: $three\n";
undef $one; undef $two; undef $three;
($one,,$three) = @onetwothree;
print "one: $one, two: $two, three: $three\n";
undef $one; undef $two; undef $three;
($one,$two,) = @onetwothree;
print "one: $one, two: $two, three: $three\n";

undef $one; undef $two; undef $three;
(undef,,$three) = @onetwothree;
print "one: $one, two: $two, three: $three\n";
