#! /usr/local/bin/perl
use warnings;
use strict;

my $string = 'http://username:password@host.domain.tld:1234/directory/file.ext?key=value#anchor';

my $blargh = $string =~ /\w+:\w+@\w+/
           ? 'yes'
           : 'no'
           ;

print "$blargh\n";
